import "@/app/globals.css";
import AuthProvider from "@/contexts/AuthProvider";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
	return (
		<html lang="en">
			<AuthProvider>
				<body className="bg-gray-100">{children}</body>
			</AuthProvider>
		</html>
	);
}
